name: jenkins_dind

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: on-failure
    networks:
      - jenkins
    environment:
      TZ: Asia/Seoul
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_certs:/certs/client:ro
    depends_on:
      - docker

  docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: unless-stopped
    networks:
      jenkins:
        aliases:
          - docker
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins_home:/var/jenkins_home
      - jenkins_certs:/certs/client
    ports:
      - "2376:2376"

volumes:
  jenkins_home:
    name: jenkins_home
  jenkins_certs:
    name: jenkins_certs

networks:
  jenkins:
    name: jenkins
    driver: bridge